### ISSUE TITLE
bug: `list_soils` sometimes returns empty strings for site description

### ISSUE THREAD

**Issue by shrouxm** [techmatters/soil-id-algorithm#120]
## Description
The `list_soils` function sometimes returns empty strings for soil series descriptions.

## Steps To Reproduce
Query `list_soils` with the coordinates `{"lat": 37.140904, "lon": -121.427414}`.

## Expected behavior
Returned soil series should all have descriptions.

## Actual behavior
Some descriptions are missing.

**Comment by CourtneyLee333** [comment]
I see this issue for every soil I've seen so far except for 1, out of about 30 soils I've looked at.

**Comment by shrouxm** [comment]
@CourtneyLee333 good point, i bumped the priority on this & will see if @jjmaynard can fix it

**Comment by DerekCaelin** [comment]
Jon finished this, sent to paul for review.

**Comment by paulschreiber** [comment]
@DerekCaelin this was deployed today.

**Comment by CourtneyLee333** [comment]
@DerekCaelin Has anyone tested this? Do we have a process for someone checking to make sure bugs are actually fixed?

**Comment by DerekCaelin** [comment]
I was able to get soil descriptions at `37.140904, -121.427414`.
