### ISSUE TITLE
Capitalization of top soil match and ecological site name is not always consistent

### ISSUE THREAD

**Issue by knipec** [techmatters/soil-id-algorithm#128]
## Repro
1. Type the following lat/long in the app's search bar: 38.00722, -121.98846
2. Click "Learn more" to bring up the location dashboard

**Expected**: Title case capitalization of Ecological Site Name: "Very Steep Shallow Fine Loamy", as most other values I've seen, like:
![Screenshot 2024-07-01 at 7 51 14 PM](https://github.com/techmatters/soil-id-algorithm/assets/5590815/9ef2be85-5e81-4823-b65e-f6bd8594655c)

**Actual**: All-caps "VERY STEEP SHALLOW FINE LOAMY"
![Screenshot 2024-07-01 at 7 43 25 PM](https://github.com/techmatters/soil-id-algorithm/assets/5590815/0bc30ed3-52da-4bdd-8ff5-109458d71531)

## Notes
I imagine the cause of this is within the soil-id-algorithm, so filing it here. Seems pretty low priority though. Thanks!

**Comment by jjmaynard** [comment]
The inconsistency is due to the SSURGO database. We'll need to reformat the text on our end for consistency.

**Comment by paulschreiber** [comment]
This change was deployed today.

**Comment by paulschreiber** [comment]
@knipec You can verify on production or staging.

**Comment by DerekCaelin** [comment]
@paulschreiber In 174beta, this is not resolved. 
<img src="https://github.com/user-attachments/assets/d39dc824-606c-4664-8188-16b849ab8f61" width="300">

API returns title case as expected, is the issue on the client site?
<img src="https://github.com/user-attachments/assets/663ffba9-d424-4ad0-9f9b-2a33237756e8" width="600">

**Comment by paulschreiber** [comment]
@DerekCaelin the popover is always all-caps, per the design.

It's fixed on the tile:
![image](https://github.com/user-attachments/assets/b8040bc0-fb4a-4b84-a131-324b8cb3237b)
