### ISSUE TITLE
Send Jon examples of 100% soil match when no data has been collected

### ISSUE THREAD

**Issue by CourtneyLee333** [techmatters/soil-id-algorithm#137]

**Comment by CourtneyLee333** [comment]
![Screenshot 2024-07-16 at 10 31 18 AM](https://github.com/user-attachments/assets/e8a019d7-689c-43b3-ac6c-6e146b2ff473)
![Screenshot 2024-07-16 at 10 31 32 AM](https://github.com/user-attachments/assets/86ef0935-236f-4da3-86ee-81513434f738)

**Comment by jjmaynard** [comment]
@CourtneyLee333 Thanks! Yes this was a bug from the old code. I've submitted a fix,  PR #138.

**Comment by CourtneyLee333** [comment]
@knipec FYI!
