### ISSUE TITLE
Update SoilWeb parsing to match API endpoint changes

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/soil-id-algorithm#139]
## Description
Update SoilWeb parsing to match API endpoint changes
- Ecological site URL
- RGB and LAB colors
- distance_m -> dist_meters

When this is fixed, confirm https://github.com/techmatters/terraso-mobile-client/issues/1786 is also fixed

**Comment by DerekCaelin** [comment]
This is being addressed

**Comment by DerekCaelin** [comment]
What is the status of this?

**Comment by DerekCaelin** [comment]
Cool, who should do the testing? Is this waiting on me?

**Comment by paulschreiber** [comment]
No. Garo/Jon/Paul need to look in to this.

**Comment by paulschreiber** [comment]
Testing is complete. Waiting for Dylan to move the code to the production server.
