### ISSUE TITLE
Remove duplicated slice_and_aggregate_soil_data code

### ISSUE THREAD

**Issue by paulschreiber** [techmatters/soil-id-algorithm#36]
## Description
We currently have both `slice_and_aggregate_soil_data_old()` and `slice_and_aggregate_soil_data()` functions.

We should remove one of them (and rename the other if needed).

**Comment by jjmaynard** [comment]
I updated the slice_and_aggregate_soil_data function and remove the slice_and_aggregate_soil_data_old()

**Comment by paulschreiber** [comment]
@jjmaynard This will get closed once #49 is merged.
